### ISSUE TITLE
Update build.xml to pull in new v1.40 C compiler

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT-core#108]
During the build process, we should now pull in the v1.40 release of the Chipkit C compiler : https://github.com/chipKIT32/chipKIT-compiler-builds

**Comment by ricklon** [comment]
Thanks. I'll get on that.
--Rick

On Wed, Nov 4, 2015 at 7:41 PM, Brian Schmalz <notifications@github.com>
wrote:

> Assigned #108 <https://github.com/chipKIT32/chipKIT-core/issues/108> to
> @ricklon <https://github.com/ricklon>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT-core/issues/108#event-455191037>.
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by ricklon** [comment]
I can get it done today. The one thing would be great is for these files to have a checksum that comes with them. Currently, to make package.json I have do the following to create checksums:
```
<target name="checksum-pic32tools">
    <checksum algorithm="SHA-256" fileext=".asc" forceOverwrite="yes">
      <fileset dir="tmp">
        <include name="pic32-tools*.zip"/>
      </fileset>
    </checksum>
  </target>
```

**Comment by EmbeddedMan** [comment]
Rick, I don't think that's unreasonable at all.  I'll poke Jason about it. For now, can we proceed with your above hack until the compiler comes with it's own checksum?

**Comment by ricklon** [comment]
Yep. I'll proceed as normal. Working on adding it in now.



On Sat, Nov 14, 2015 at 2:34 PM, Brian Schmalz <notifications@github.com>
wrote:

> Rick, I don't think that's unreasonable at all. I'll poke Jason about it.
> For now, can we proceed with your above hack until the compiler comes with
> it's own checksum?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT-core/issues/108#issuecomment-156738862>
> .
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by EmbeddedMan** [comment]
I have confirmed that chipKIT-core build.xml file is downloading pic32-tools from the v1.40rc2 release.
