### ISSUE TITLE
SERIAL_PORT_MONITOR definition missing

### ISSUE THREAD

**Issue by xxxajk** [chipKIT32/chipKIT-core#111]
Just as it is said in the title. 
As long as there is a serial interface, even if this is emulated in USB SERIAL_PORT_MONITOR should point to it.
There are actually a bunch of missing defines, and they need to be somewhere.
Here is an example from the mega variant's "arduino_pins.h"

```
// These serial port names are intended to allow libraries and architecture-neutral
// sketches to automatically default to the correct port name for a particular type
// of use.  For example, a GPS module would normally connect to SERIAL_PORT_HARDWARE_OPEN,
// the first hardware serial port whose RX/TX pins are not dedicated to another use.
//
// SERIAL_PORT_MONITOR        Port which normally prints to the Arduino Serial Monitor
//
// SERIAL_PORT_USBVIRTUAL     Port which is USB virtual serial
//
// SERIAL_PORT_LINUXBRIDGE    Port which connects to a Linux system via Bridge library
//
// SERIAL_PORT_HARDWARE       Hardware serial port, physical RX & TX pins.
//
// SERIAL_PORT_HARDWARE_OPEN  Hardware serial ports which are open for use.  Their RX & TX
//                            pins are NOT connected to anything by default.
#define SERIAL_PORT_MONITOR         Serial
#define SERIAL_PORT_HARDWARE        Serial
#define SERIAL_PORT_HARDWARE1       Serial1
#define SERIAL_PORT_HARDWARE2       Serial2
#define SERIAL_PORT_HARDWARE3       Serial3
#define SERIAL_PORT_HARDWARE_OPEN   Serial1
#define SERIAL_PORT_HARDWARE_OPEN1  Serial2
#define SERIAL_PORT_HARDWARE_OPEN2  Serial3
```

**Comment by EmbeddedMan** [comment]
These will have to go in the variant file for each board we support, as they will be different for different boards. Also, the new Harmony USB integration will re-jigger these around even on the same board.

**Comment by xxxajk** [comment]
Since I only have the UNO32, I only made the recommendation, and no patch, but yes, that would be an issue, however I don't think all is lost.
The general idea used by the Arduino team is to use something along the lines of some sort of sane defaults, which is better than no definition whatsoever. There is also always the ability to add extra menu items in order to control the outcome and get what you want.

What I have done in the upcoming UHS 3.0 is to implement all code into inline coded headers, and allow the user to define options in the sketch. For example, see line 9 at https://github.com/felis/UHS30/blob/master/libraries/USB_HOST_SHIELD/examples/TWO_HOSTS_BULK/TWO_HOSTS_BULK.ino
Notice that while serial debug output is configured within the library, that there is a way to override it. In order for me to support the UNO32, and other microchip based boards out-of-the-box, at least some sort of output default is needed. It does not have to be the "Serial" class, even a USB serial class is fine, like on the DUE and Zero.

While the following idea won't work well for something that is a core, it could work out if Serial were to be moved to an inline library, but then you do have the issue of having to include it in the sketch, which unfortunately is not how the Arduino team originally did it. They assumed some things would always be there, even if you did not use them -- which can bloat the binary. Unfortunately they also automatically have Arduino.h included too before anything else, and do other evil rewrites of the sketch, such as prototyping the contents. Fortunately there are some other ways around these problems, but I am already beyond the scope of the fix request already.

**Comment by xxxajk** [comment]
So still no fix for this, or #114? Come on, it's not like it is rocket science.

**Comment by JacobChrist** [comment]
Pull requests welcome.

**Comment by xxxajk** [comment]
I've been quite busy, I'll try to get this in this morning... I usually code/work at night 8-)

**Comment by xxxajk** [comment]
Finally got to this.
https://github.com/chipKIT32/chipKIT-core/pull/247

**Comment by xxxajk** [comment]
long long ago merged, closing.
