### ISSUE TITLE
Consider renaming Raspberrypi target to ARM target

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT-core#13]
Consider renaming Raspberrypi target to ARM target

The compiler and pic32prog supports a kind of arm processor more than just raspberrpi. Some testing would be needed before this change would go in place.

--Rick

**Comment by EmbeddedMan** [comment]
I believe that this is now the case. Our ARM builds now no longer reference Raspberry Pi, for example chipkit-core-arm.16778039.HEAD-v1.0.1-53-gf7436d5.zip
