### ISSUE TITLE
Copy startup code from chipKIT32-MAX repo

### ISSUE THREAD

**Issue by jasonkajita** [chipKIT32/chipKIT-core#145]
Copy startup code from https://github.com/chipKIT32/chipKIT32-MAX/commit/35a91c791478a1b98bdd3610c6c199444df22ed4

**Comment by EmbeddedMan** [comment]
This needs to be confirmed by somebody (Keith) that can properly test that this change is working as intended.

**Comment by EmbeddedMan** [comment]
Keith, have you confirmed that the startup code you need is now included properly?

**Comment by KeithV** [comment]
Looks good you can close
