### ISSUE TITLE
SPI assumed DSPI0 and taskmanager assumed unsigned IDs

### ISSUE THREAD

**Issue by KeithV** [chipKIT32/chipKIT-core#167]
SPI assumed DSPI0 and taskmanager assumed unsigned IDs
See PR 166

**Comment by EmbeddedMan** [comment]
Fixed in PR #166

**Comment by KeithV** [comment]
Brian,

 

With this update I am able to run the Wire code again. I don’t seem to have access to the chipKIT.net forum, so you can close that out as resolved.

 

KeithV
