### ISSUE TITLE
Missing Ram quantity

### ISSUE THREAD

**Issue by Testato** [chipKIT32/chipKIT-core#174]
Normally the Arduino IDE write in the consolle the Ram fisically available at the end of Verify process.
Instead this core write only the Ram used.

**Comment by EmbeddedMan** [comment]
Ahh, yes, I see that now! I will fix this. Thanks so much for creating this issue.

**Comment by Testato** [comment]
Thabks to you for this core.
I opened a topic on Italian Arduino forum for this core and hope many people will test it ;-)
http://forum.arduino.cc/index.php?topic=380375.0

**Comment by EmbeddedMan** [comment]
Fixed!

**Comment by JacobChrist** [comment]
Nice, thanks Brian.
