### ISSUE TITLE
Syntax highlighting for Serial0 does not work (Fubarino SD)

### ISSUE THREAD

**Issue by JacobChrist** [chipKIT32/chipKIT-core#186]
The text is black when it should be orange.

**Comment by EmbeddedMan** [comment]
Turns out this is hard-coded in the Arduino IDE. I have added Serial0 in a pull request to Arduino, and if they accept it, then we'll have this issue fixed in whatever version of Arduino IDE incorporates the change.

**Comment by EmbeddedMan** [comment]
OK, turns out you can actually have a keywords.txt file in your platform directory. I'm going to add this for us, and put the Serial0 keyword in there. No need to change the Arduino IDE.

**Comment by EmbeddedMan** [comment]
This is now fixed and will be in the next version. Thanks for reporting it Jacob!
