### ISSUE TITLE
Windows zip filename is automatically selected as the filename of the directory

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT-core#19]
Windows zip file name is automatically selected the file name as the directory. This means changing the way the file is compressed, and promote the chipkit-core directory and just zip it's contents for Windows.

**Comment by EmbeddedMan** [comment]
Is this still the case? It seems that the Windows .zip file is being build correctly now, as you can easily unzip it and drop the chipkit folder in place and it works. Maybe close this issue?

**Comment by ricklon** [comment]
I've confirmed it's being built correctly now.
