### ISSUE TITLE
Board_Defs.h OPT_BOARD_INTERNAL

### ISSUE THREAD

**Issue by xxxajk** [chipKIT32/chipKIT-core#198]
Why are all the handy BASE and IRQ define statements disabled as something "Internal"?
Having them unavailable to libraries and sketches makes it a total nightmare for developing anything that wants to use a custom IRQ for any PIC32, causing one to have to copy and paste from all the Board_Defs.h, then ifdef for each board when this is already provided.
Huge mistake. Mind if I fix this and issue another PR?

**Comment by EmbeddedMan** [comment]
By all means submit a PR.

Those seem like something that should go in the p32_defs.h file, no?

*Brian

**Comment by xxxajk** [comment]
Submitted PR #199
Can continue discussions there, so closing.
