### ISSUE TITLE
variants directly linker scripts not on the correct paths

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT-core#20]
variants directly linker scripts not on the correct paths

**Comment by ricklon** [comment]
This might actually be the board name problem in issue #29 .

**Comment by ricklon** [comment]
The fix is to add the linker patch and the linker to the boards.txt file.

**Comment by EmbeddedMan** [comment]
I believe this issue has been fixed. Every board now compiles properly in chipKIT-core, including the ones that use their own linker scripts in their own variants folder.
