### ISSUE TITLE
Board.define doesn't exist in Arduino boards.txt file

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT-core#24]
Board  level defines don't exist in current Arduino.  Any board that uses that will file under Arduino. 

Temp Solution is to add a build.extra_flags to your board. 

Example this breaks USB Serial for Fubarino boards.

**Comment by EmbeddedMan** [comment]
Both now exists in the boards.txt file, for example
fubarino_mini_dev.board.define=-D_USE_USB_FOR_SERIAL_
fubarino_mini_dev.build.extra_flags=-D_USE_USB_FOR_SERIAL_
for all boards that require USE_USB_FOR_SERIAL
