### ISSUE TITLE
Should drivers be included with the core download?

### ISSUE THREAD

**Issue by rianders** [chipKIT32/chipKIT-core#26]
Should drivers be included with the core download?

**Comment by ricklon** [comment]
Confirmed. This should be done. A new directory called drivers will be added.

**Comment by ricklon** [comment]
This should just be for Windows builds.

**Comment by ricklon** [comment]
This is definitely more complicated when using the package json file.  The files are not easily accessible from the package directory.

**Comment by JacobChrist** [comment]
I agree, these are missing, and I was about to add this issue.

**Comment by EmbeddedMan** [comment]
Rick, I think that we should create a 'drivers' .zip file (just for windows) and include it as an additional 'tool' dependency in the .json file. We could then upload that zip file into the release for chipKIT-core. I think this is something I can do.

However, you'll also need to edit the build.xml file to include the drivers.zip file in the normal Windows .zip file for the whole package (for manual installs). 

Does this sound like the right thing to do?

**Comment by ricklon** [comment]
That sounds great.  I can get crackin' on that.

--Rick

On Tue, Jan 5, 2016 at 10:14 PM, Brian Schmalz <notifications@github.com>
wrote:

> Rick, I think that we should create a 'drivers' .zip file (just for
> windows) and include it as an additional 'tool' dependency in the .json
> file. We could then upload that zip file into the release for chipKIT-core.
> I think this is something I can do.
>
> However, you'll also need to edit the build.xml file to include the
> drivers.zip file in the normal Windows .zip file for the whole package (for
> manual installs).
>
> Does this sound like the right thing to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT-core/issues/26#issuecomment-169207486>
> .
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by EmbeddedMan** [comment]
So I've created a drivers.zip file that I'm temporarily hosting on my EmbeddedMan GitHub repo release. We'll add that file to the chipKIT-core release v1.1.0 binary file list. However, how are you going to incorporate this drivers directory into the 'manual copy' chipKIT-core distribution Rick?

**Comment by ricklon** [comment]
Can you sign the file too? I can do a local signing if needed. The plan was
to pull it into the ./tmp directory. Then when a build is called bundle it
into the distro for manual. I've not worked out the separate download in
JSON yet.

On Wed, Jan 6, 2016 at 9:48 PM, Brian Schmalz <notifications@github.com>
wrote:

> Assigned #26 <https://github.com/chipKIT32/chipKIT-core/issues/26> to
> @ricklon <https://github.com/ricklon>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT-core/issues/26#event-507803160>.
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by EmbeddedMan** [comment]
Rick,

Hmm. Each of the two drivers included in the .zip file is already signed.
Why does the enclosing zip file also need to be signed? (I'm not even
really sure how to do that for just a zip file honestly.)

I've already worked out the separate download in the json file - that part
is done and working great. (See the EmbeddedMan json)

One of my questions is where should the build.xml process pull the windows
driver .zip file from? Right now it's in my EmbeddedMan/chipKIT-core
release, but I don't think that's a good place to put it long term. Maybe
it needs its own little separate repo?

*Brian

**Comment by ricklon** [comment]
It should really be in it's own repo so that changes can be tracked and it would get pulled to the tmp directory.  Then will windows build occurs it would be retrieved from the release directory moved to the drivers folder.

Being in it's own release directy with a signature should allow it to be downloaded into tools for windows via the package.json technic. I hope.

**Comment by EmbeddedMan** [comment]
Rick,

I'll put it in it's own repo then. But it doesn't need a signature to be
downloaded by .json file.We just need to put the accurate file size and
SHA256 value of the file in the .json file. Both drivers are already
signed, so Windows doesn't need anything more than that.

*Brian

**Comment by ricklon** [comment]
These drivers included now. I've confirmed that it works.
