### ISSUE TITLE
Split up analogRead() so that it can be used both as blocking and non-blocking.

### ISSUE THREAD

**Issue by JacobChrist** [chipKIT32/chipKIT-core#289]
The proposed changes would split the existing analogRead() into three functions.

o. One to start the conversion.
o. One to check if the conversion is complete.
o. One to read the converted value.

int analogRead(uint8_t pin)
{
  _analogReadConversionStart(pin);
  while( ! _analogReadConversionComplete() );
  return _analogReadConversion();
}

This code is already complete and part of some bigger changes.  This issue is being added so that pull requests and specific commits can be rolled back should the changes cause an issue.

**Comment by EmbeddedMan** [comment]
This code is now merged in.
