### ISSUE TITLE
Arduino uses slightly different variables in boards.txt, and platforms.txt build.board vs fubarino_sd.BOARD

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT-core#29]
Arduino uses slightly different variables in boards.txt, and platforms.txt build.board vs fubarino_sd.BOARD

All board names need fixing because of the difference.
fubarino_sd.build.board=BOARD_FUBARINO_SD_

**Comment by EmbeddedMan** [comment]
All boards in the boards.txt file are now of the form:
fubarino_mini_dev.board=_BOARD_FUBARINO_MINI_
which I think satisfies this issue.
