### ISSUE TITLE
A few defines to make porting easier.

### ISSUE THREAD

**Issue by GrahamM** [chipKIT32/chipKIT-core#302]
I've noted that there's a fair bit of work done to make porting Arduino libraries over much easier, especially around program memory functions. However, there's still a few that I've encountered that'd be nice not to have to deal with, including:
strlen_P
strlen_P
strnlen_P
strncmp_P
strncat_P
strncpy_P

PGM_VOID_P

Any chances we can get these in pgmspace.h?

**Comment by majenkotech** [comment]
I'm surprised they aren't there already. They should be since they are PGM versions of normal functions.

**Comment by GrahamM** [comment]
Sweet - thanks!
