### ISSUE TITLE
Add multi-SPI port example for DSPI library

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT-core#349]
It would be really nice to have some very simple DSPI examples, like one that just shows how to use multiple SPI ports, and another that shows how to use DSPI's interrupt feature.

**Comment by EmbeddedMan** [comment]
I created two sketches (DSPI_Demo and DSPI_Int_Demo). They show using three hardware SPI ports on a Fubinaro SD. Here are the logic analyzer traces  for each.

This first one is the DSPI_Demo sketch. You can see three different transactions, each with three bytes, on three separate SPI ports. They each happen at a different speed as well. Click to embiggen.

![dspi_demo](https://cloud.githubusercontent.com/assets/450056/25922346/802de4e2-359e-11e7-9663-b622ea98eced.PNG)

And here is the DSPI_Int_Demo sketch output. Similar setup, but this time using SPI interrupts, so we can do other things while data is transferring in the background. Click to embiggen.

![dspi_int_demo](https://cloud.githubusercontent.com/assets/450056/25922390/add7a64e-359e-11e7-97de-106ec7bd6e1c.PNG)

**Comment by majenkotech** [comment]
Nice.

Can I put it a request for a "README.md" file to be added to new (and existing if people ever get time and a round tuit) examples? UECIDE now has an Examples Browser and will display it (as Markdown) when you select the example. Also it will (or should) show up in Github nicely.

Just a brief overview of what it is and how you use it will do.

**Comment by EmbeddedMan** [comment]
Yeah! That's a great idea. I'll do that for these examples.

**Comment by EmbeddedMan** [comment]
Pull request merged.
