### ISSUE TITLE
Implement USBSerial::availableForWrite

### ISSUE THREAD

**Issue by eric-wieser** [chipKIT32/chipKIT-core#355]
Since this was omitted from #353

**Comment by EmbeddedMan** [comment]
@majenkotech Does the new USB stack implement this call?

**Comment by majenkotech** [comment]
Yes, it does.

**Comment by majenkotech** [comment]
```C++
int CDCACM::availableForWrite() {
    return (CDCACM_BUFFER_SIZE + _txTail - _txHead) % CDCACM_BUFFER_SIZE;
}
```

**Comment by EmbeddedMan** [comment]
OK, @eric-wieser , we are merging in a whole new USB stack soon which will have this call implemented. Once that happens, this issue can be resolved.

**Comment by majenkotech** [comment]
This is now complete.

**Comment by EmbeddedMan** [comment]
I'm closing this issue, since the new core 2.x.x has been released with the new USB stack.
