### ISSUE TITLE
File size incorrect

### ISSUE THREAD

**Issue by majenkotech** [chipKIT32/chipKIT-core#365]
https://github.com/chipKIT32/chipKIT-core/blob/239946479b0069d01410f53affa86b1174684551/package_chipkit_index.json#L89

The file size of 7674509 is incorrect. It should be 7674539.

**Comment by EmbeddedMan** [comment]
OK, should be fixed. I'll close when Rick reports it's working for him.

**Comment by majenkotech** [comment]
Glad you noticed I linked to the wrong line number there - just checking you were awake ;)

Testing it now.

**Comment by majenkotech** [comment]
That's fixed it for me. Install, uninstall, reinstall, success.

**Comment by EmbeddedMan** [comment]
Fixed for me too. Thanks so much for finding the problem Matt!

**Comment by majenkotech** [comment]
You'd think the IDE would check the size after download, wouldn't you...?

**Comment by EmbeddedMan** [comment]
Rick has confirmed that this is now working for him.
