### ISSUE TITLE
Looks like small mistake in USB.cpp - VID_MICROCHIP should be VID_MCHP

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT-core#376]
Looks like the line on 88 needs to be changed from VID_MICROCHIP to VID_MCHP.

Can you confirm that this change is correct?

Also, what about line 73 - are you sure should we be using VID_FUTURE with PID_CDCACM?  I think that's correct (as I think it's what we were using before) but I just want to confirm.

**Comment by majenkotech** [comment]
Yes, using FUTURE for the pure CDCACM mode is correct. We were using that before, so we should keep using it - but only for the same mode that we used to have as the only mode available.

**Comment by majenkotech** [comment]
Fixed in #377

**Comment by EmbeddedMan** [comment]
This issue has been confirmed closed in chipKIT-core v2.0.1
