### ISSUE TITLE
Create the 'json' thing so that Arduino IDE can suck down the core by itself

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT-core#4]
I'm not sure exactly what's involved, but this core should have this functionality. :-)

**Comment by ricklon** [comment]
The first version is added, but it is incomplete. More work needs to be done in packaging parts of the project for this file.

1. Automatic generation of the index.json is needed
2. pic32-gcc compiler
* download link by OS
* version number
* checksum 
* file size
3. pic32-prog 
* download link by OS
* version number
* checksum 
* size
4. chipKIT-core 
* download by OS if needed
* version number
* checksum
* size

Currently, we bundle as one group download. That is really easy. Less work.

In this version we need to make sure each portion has a home, and we can collect the correct information for the file.

Doing this manually once is OK, but this should be part of the build process in the future.

**Comment by ricklon** [comment]
OK. I've got a strategy. For chipKIT-core we'll use tagged releases.
https://github.com/blog/1547-release-your-software

 That way the "core" can have a url and be downloaded easily. For a test I added the tag 1.6.0. The release system for Github uses semantic versioning major.minor.patch.

**Comment by EmbeddedMan** [comment]
Sweet Rick. This looks like a great way to go. Wouldn't it be better to
have an independent version number from the Arduino IDE? In other words,
our core's first public release build should be 1.0.0, right?

*Brian

**Comment by ricklon** [comment]
That can be done.  I'll check into in.

--Rick

On Mon, Sep 14, 2015 at 10:35 AM, Brian Schmalz <notifications@github.com>
wrote:

> Sweet Rick. This looks like a great way to go. Wouldn't it be better to
> have an independent version number from the Arduino IDE? In other words,
> our core's first public release build should be 1.0.0, right?
>
> *Brian
>
> On Mon, Sep 14, 2015 at 9:29 AM, Ricklon <notifications@github.com> wrote:
>
> > OK. I've got a strategy. For chipKIT-core we'll use tagged releases.
> > https://github.com/blog/1547-release-your-software
> >
> > That way the "core" can have a url and be downloaded easily. For a test I
> > added the tag 1.6.0. The release system for Github uses semantic
> versioning
> > major.minor.patch.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/chipKIT32/chipKIT-core/issues/4#issuecomment-140098942>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT-core/issues/4#issuecomment-140100448>
> .
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by ricklon** [comment]
Ok. We can actually upload custom files when the release is created. These uploaded files can be the files for checksums and other custom files we might need.

1. Will need expand auto generating JSON file to auto generating release files and uploading them.
 * manual solution be worked through
 * manual documentation will be posted in this issue thread

2. pic32-gcc compiler. We need checksum and file size.
 * Can be solved by having those file in the same directory as the download location or moving them to our release location and then generating checksum.
* Would be better to do in current and future build locations 

3. Build and upload pic32-prog version we use plus the check sum

4. chipKIT-core can be downloaded and the checksum is uploaded for each release.

**Comment by EmbeddedMan** [comment]
Rick, what's the status of this item? Is there anything I can test out for you, or help you with, to try and make it happen?

**Comment by ricklon** [comment]
I figured out how github releases work.  I think I've made all the short
term decisions.  tonight I'll be at Fubar to get a rough release ready.

I need to add checksums,  and Curl support to ANT build.xml.

If pic32prog and pic32-gcc had releases with checksums.  Everything would
be much easier.

--Rick

**Comment by EmbeddedMan** [comment]
Is there any information on how to generate these cheksums and make them
available? I could work on that if I had some breadcrumbs.

*Brian

**Comment by ricklon** [comment]
ANT checksum:
https://ant.apache.org/manual/Tasks/checksum.html

GITHUB curl tutorial:
https://gist.github.com/caspyin/2288960

ANT Restful interaction using "curl":
http://stackoverflow.com/questions/2354509/restful-httpclient-for-ant

We need to create checksum for pic32gcc,  pic32prog,  and chipKIT-core
download file.

These all then need to uploaded into a Github release for chipKIT core.
That way these big binaries are not tracked in out Github repo.

Other option is to load  everything into Amazon s3 using the amazon upload
s3 task in the build.xml file.

--Rick




On Tue, Sep 15, 2015 at 5:42 PM, Brian Schmalz <notifications@github.com>
wrote:

> Is there any information on how to generate these cheksums and make them
> available? I could work on that if I had some breadcrumbs.
>
> *Brian
>
> On Tue, Sep 15, 2015 at 4:31 PM, Ricklon <notifications@github.com> wrote:
>
> > I figured out how github releases work. I think I've made all the short
> > term decisions. tonight I'll be at Fubar to get a rough release ready.
> >
> > I need to add checksums, and Curl support to ANT build.xml.
> >
> > If pic32prog and pic32-gcc had releases with checksums. Everything would
> > be much easier.
> >
> > --Rick
> >
> > On Tue, Sep 15, 2015, 5:20 PM Brian Schmalz <notifications@github.com>
> > wrote:
> >
> > > Rick, what's the status of this item? Is there anything I can test out
> > for
> > > you, or help you with, to try and make it happen?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/chipKIT32/chipKIT-core/issues/4#issuecomment-140548406>
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/chipKIT32/chipKIT-core/issues/4#issuecomment-140552987>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT-core/issues/4#issuecomment-140555184>
> .
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by ricklon** [comment]
This is moving forward. Checksums are working, manual releases are possible. Need to determine best way to bundle pic32prog.

I've abandoned having ANT build the release  automatically. It has problems echoing files and showing their file names, and file sizes. The only solution so far was to do a direct call to the operating system.  If the ANT had better flags and options the following would have led to a decent solution:

```
  <fileset id="zipfiles" dir="tmp" casesensitive="yes">
        <include name="pic32-tools*.zip"/>
    </fileset>
    <property name="prop.zipfiles" refid="zipfiles"/>
    <echo>${prop.zipfiles}</echo>
    <concat>
      <fileset dir="tmp">
        <include name="pic32-tools*.asc"/>
      </fileset>
    </concat>
```

**Comment by ricklon** [comment]
Status:
pic32-tools/gcc compiler posted with proper checksum
pic32-prog created and posted with proper checksum

package json needs to be updated with the following:
* pic32-prog location, checksum, size
* The actual core release needs a checksum.

Then the URL testing can commence.


-_Rick

On Tue, Sep 15, 2015 at 5:58 PM, Rick Anderson <rick.rickanderson@gmail.com>
wrote:

> ANT checksum:
> https://ant.apache.org/manual/Tasks/checksum.html
>
> GITHUB curl tutorial:
> https://gist.github.com/caspyin/2288960
>
> ANT Restful interaction using "curl":
> http://stackoverflow.com/questions/2354509/restful-httpclient-for-ant
>
> We need to create checksum for pic32gcc,  pic32prog,  and chipKIT-core
> download file.
>
> These all then need to uploaded into a Github release for chipKIT core.
> That way these big binaries are not tracked in out Github repo.
>
> Other option is to load  everything into Amazon s3 using the amazon upload
> s3 task in the build.xml file.
>
> --Rick
>
>
>
>
> On Tue, Sep 15, 2015 at 5:42 PM, Brian Schmalz <notifications@github.com>
> wrote:
>
>> Is there any information on how to generate these cheksums and make them
>> available? I could work on that if I had some breadcrumbs.
>>
>> *Brian
>>
>> On Tue, Sep 15, 2015 at 4:31 PM, Ricklon <notifications@github.com>
>> wrote:
>>
>> > I figured out how github releases work. I think I've made all the short
>> > term decisions. tonight I'll be at Fubar to get a rough release ready.
>> >
>> > I need to add checksums, and Curl support to ANT build.xml.
>> >
>> > If pic32prog and pic32-gcc had releases with checksums. Everything would
>> > be much easier.
>> >
>> > --Rick
>> >
>> > On Tue, Sep 15, 2015, 5:20 PM Brian Schmalz <notifications@github.com>
>> > wrote:
>> >
>> > > Rick, what's the status of this item? Is there anything I can test out
>> > for
>> > > you, or help you with, to try and make it happen?
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/chipKIT32/chipKIT-core/issues/4#issuecomment-140548406
>> >
>> >
>> > > .
>> > >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/chipKIT32/chipKIT-core/issues/4#issuecomment-140552987
>> >
>> > .
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/chipKIT32/chipKIT-core/issues/4#issuecomment-140555184>
>> .
>>
>
>
>
> --
> Co-founder
> Fair Use Building and Research (FUBAR) Labs
> http://fubarlabs.org
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by ricklon** [comment]
First successful download. Current error:
```
Could not find boards.txt in /Users/mmm/Library/Arduino15/packages/chipKIT-core/hardware/pic32/1.6.0. Is it pre-1.5?
Could not find boards.txt in /Users/mmm/Library/Arduino15/packages/chipKIT-core/hardware/pic32/1.6.0. Is it pre-1.5
```

**Comment by ricklon** [comment]
Ok. This is because the package directory hierarchy is:
~/Library/Arduino15/packages/chipKIT-core/hardware/pic32/1.6.0

So the "core" needs to be placed inside the 1.6.0 directory when zipped. Modifying the github-release target show fix this.

**Comment by ricklon** [comment]
Still having problem with the format of the zip file for core. It's unclear exactly there error. I'll have to examine how other people do it and reread the docs.

**Comment by ricklon** [comment]
We can get the compilers from here now:
https://github.com/chipKIT32/chipKIT-compiler-builds/releases

**Comment by EmbeddedMan** [comment]
YES! This is actually working now. The Wiki has been updated with instructions for how to use the new json file. (http://chipkit.net/wiki/index.php?title=ChipKIT_core) Tested on MacOS X, Windows, Linux32 and Linux64. (Linux64 still requires 32-bit compatibility libraries though since we don't have a 64 bit compiler yet)
