### ISSUE TITLE
ldscript path need to specify if it is in core or the variant folder.

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT-core#40]
ldscript path need to specify if it is in core or the variant folder.

Add the ldscript path for each board.

**Comment by ricklon** [comment]
By default build.ldscript.path points to the build.core.path.
Each board then needs to override the setting in case the are using an ldscript in the variant file in boards.txt.
chipkit_WiFire.build.ldscript.path={build.variant.path}

**Comment by EmbeddedMan** [comment]
This has been added to platform.txt and is now working as it should. Yea!
