### ISSUE TITLE
Bootloader not supported error message appears

### ISSUE THREAD

**Issue by ricklon** [chipKIT32/chipKIT-core#45]
Bootloader not supported. Error messages occurs but doesn't affect programming with pic32prog.

Bootloader file specified but missing: /Users/rickanderson/Documents/Arduino/hardware/chipkit-core/pic32/bootloaders/not-supported

**Comment by ricklon** [comment]
This shouldn't be happening any more. Need to confirm closed.

**Comment by EmbeddedMan** [comment]
I have confirmed this is no longer an issue. Pic32prog now works for every board we support.
