### ISSUE TITLE
chipKit-core is unsuable on macOS Catalina

### ISSUE THREAD

**Issue by yannip1234** [chipKIT32/chipKIT-core#457]
I cannot use my uC32 on my mac. I get bad CPU errors and cannot find picg++ errors. Is this still being updated?

**Comment by majenkotech** [comment]
Yes, we know. There are many many things that don't work on Catalina. At the moment we're waiting for a new 64-bit compiler from Microchip.

**Comment by yannip1234** [comment]
Great, thanks for the prompt reply!

**Comment by majenkotech** [comment]
I would suggest, if you don't have another computer available, installing a version of a Linux operating system in a virtual machine (VMWare, maybe) and use the IDE in that.
