### ISSUE TITLE
ChipKIT won't work on M1 arm Macs

### ISSUE THREAD

**Issue by crunchysteve** [chipKIT32/chipKIT-core#488]
ChipKIT direct board install in ArduinoIDE won't work on M1 arm Macs, gives an error about incorrect executable. Tried old 1.8 IDE (had to use the load old IDE hack to even install it) and Arduino IDE 2.2.1. Running gen 1 MacBook Air, MacOS Sonoma 14.1.2, Rosetta2 for intel back-compatibility. Non-urgent.

**Comment by JacobChrist** [comment]
The compiler is 32-bit and doesn't work on 64-bit Macs.  It not likely to get fixed since Microchip was the maintainer of the compiler and no one is working on it.

**Comment by crunchysteve** [comment]
Thanks for the headsup.
