### ISSUE TITLE
Dependencies on plib.h

### ISSUE THREAD

**Issue by jasonkajita** [chipKIT32/chipKIT-core#79]
According to our test team, the following boards require plib.h:

* chipKIT DP32
* chipKIT Pi
* chipKIT Pi USB_Serial
* chipKIT cmod

and therefore won't compile with the upcoming chipKIT compiler version.

**Comment by EmbeddedMan** [comment]
This issue should now be fixed. However, I would appreciate it if somebody went through and confirmed that plib.h is NOT referenced anywhere in any of our core files, variant files, or libraries before we close this out.

**Comment by mariusgeanta** [comment]
I can confirm that in the current version of chipKIT-core plib.h is not referenced anymore.
