### ISSUE TITLE
Add build.path to include list

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT-core#81]
The build.path (the temporary folder where everything gets copied to before the compile happens) should be added to the list of include paths on the compiler command line, so that any .h files that are in the sketch folder can be included in our sketches and libraries.

**Comment by EmbeddedMan** [comment]
I believe this issue has been fixed. Please confirm.

**Comment by EmbeddedMan** [comment]
Keith, I believe you are the one who found this issue in the first place. Can you confirm here that this is fixed to your satisfaction?

**Comment by EmbeddedMan** [comment]
Keith, did you have a chance to confirm that this issue has been addressed to your satisfaction?

**Comment by KeithV** [comment]
This works,but you might have a redundant include to the build directory that is no longer used. You only need the build\sketch directory. If that is fixed you can close.

**Comment by EmbeddedMan** [comment]
Keith - thanks! I have fixed the redundant build directory as well.
