### ISSUE TITLE
Bring Wire.cpp up to date with MPIDE's version

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/chipKIT-core#95]
Keith made some awesome changes in MPIDE's version of Wire.cpp, including fixing some bugs related to repeated start conditions and properly returning the right return codes from endTransmission(); (according to Arduino's documentation).

**Comment by EmbeddedMan** [comment]
This should issue should be fixed. Please confirm.

**Comment by EmbeddedMan** [comment]
Keith, can you double check that the current Wire.cpp has your changes?

**Comment by EmbeddedMan** [comment]
Keith, still looking for confirmation that the wire changes got made properly.

**Comment by KeithV** [comment]
Looks good, you can close
